export type ToolItem = {
    id: string;
    title: string;
    subtitle: string;
    pricePerDay: number;
    deposit: number;
    description: string;
  };
  
  export const tools: ToolItem[] = [
    {
      id: "1",
      title: "Лентошлифовальная машина",
      subtitle: "Зубр ЗЛШМ-76-950",
      pricePerDay: 500,
      deposit: 5000,
      description: "Инструмент для шлифовки различных поверхностей.",
    },
    {
      id: "2",
      title: "Паяльник полипропилена",
      subtitle: "black gear",
      pricePerDay: 600,
      deposit: 5000,
      description: "Инструмент для пайки полипропиленовых труб.",
    },
    {
      id: "3",
      title: "УШМ 125",
      subtitle: "max pro 680W",
      pricePerDay: 350,
      deposit: 5000,
      description: "Компактная болгарка для бытовых и строительных работ.",
    },
    {
      id: "4",
      title: "Дрель тихоходная с микроударом",
      subtitle: "AEG DB1500-2XE",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Подходит для сверления различных материалов.",
    },
    {
      id: "5",
      title: "Рубанок",
      subtitle: "Интерскол P-110/1100M",
      pricePerDay: 600,
      deposit: 5000,
      description: "Электрорубанок для обработки древесины.",
    },
    {
      id: "6",
      title: "Фрезер",
      subtitle: "RYOBI RRT 1600",
      pricePerDay: 800,
      deposit: 5000,
      description: "Ручной фрезер для дерева и других материалов.",
    },
    {
      id: "7",
      title: "Пневмопистолет Toua",
      subtitle: "Toua GSN 50",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Пневмопистолет для монтажных работ.",
    },
    {
      id: "8",
      title: "Фен строительный",
      subtitle: "Интерскол ФЭ-2000",
      pricePerDay: 350,
      deposit: 5000,
      description: "Строительный фен для нагрева и сушки материалов.",
    },
    {
      id: "9",
      title: "Плазморез",
      subtitle: "ПТК RILON CUT 60 C",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Аппарат плазменной резки металла.",
    },
    {
      id: "10",
      title: "Газовый гвоздезабивной пистолет",
      subtitle: "Toua GFN3490CH-C",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Газовый пистолет для забивания гвоздей по дереву.",
    },
    {
      id: "11",
      title: "Бетономешалка 63 л",
      subtitle: "Земляк БСЭ-63",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Компактная бетономешалка для строительных работ.",
    },
    {
      id: "12",
      title: "Клупп",
      subtitle: "SQ30-2C",
      pricePerDay: 1500,
      deposit: 5000,
      description: "Инструмент для нарезки резьбы на трубах.",
    },
    {
      id: "13",
      title: "УШМ 230",
      subtitle: "Metabo W2200-230",
      pricePerDay: 800,
      deposit: 5000,
      description: "Мощная углошлифовальная машина большого диаметра.",
    },
    {
      id: "14",
      title: "Циклевочная машина",
      subtitle: "Мисон СО-206",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Машина для обработки деревянных полов.",
    },
    {
      id: "15",
      title: "Отбойный молоток",
      subtitle: "Favorit",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Инструмент для демонтажных работ.",
    },
    {
      id: "16",
      title: "Безвоздушный краскопульт",
      subtitle: "SCHTAER Mars 20",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Оборудование для окраски безвоздушным методом.",
    },
    {
      id: "17",
      title: "Электропушка",
      subtitle: "Stand YXC-03RE",
      pricePerDay: 350,
      deposit: 5000,
      description: "Электрическая тепловая пушка для обогрева.",
    },
    {
      id: "18",
      title: "Дизельная пушка",
      subtitle: "Ganta ТПД-55",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Дизельная тепловая пушка для больших помещений.",
    },
    {
      id: "19",
      title: "Штроборез",
      subtitle: "Bosch GNF 35 CA",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Инструмент для штробления стен.",
    },
    {
      id: "20",
      title: "Пылесос",
      subtitle: "Bosch GAS 20 L SFC",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Строительный пылесос для сухой и влажной уборки.",
    },
    {
      id: "21",
      title: "Вышка тура",
      subtitle: "1,2×2,0×7,6",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Передвижная вышка для высотных работ.",
    },
    {
      id: "22",
      title: "Рехау / пресс-инструмент",
      subtitle: "Tim FT1240B-QC",
      pricePerDay: 800,
      deposit: 5000,
      description: "Инструмент для монтажа трубных систем.",
    },
    {
      id: "23",
      title: "Каток для газона",
      subtitle: "К01-00.000 50 л",
      pricePerDay: 500,
      deposit: 5000,
      description: "Каток для уплотнения и выравнивания газона.",
    },
    {
      id: "24",
      title: "Жираф",
      subtitle: "Schtaer 3000F3",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Шлифмашина для стен и потолков.",
    },
    {
      id: "25",
      title: "Газонокосилка бензиновая самоходная",
      subtitle: "ECO MX196",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Самоходная газонокосилка со срезом 51 см.",
    },
    {
      id: "26",
      title: "Тепловизор",
      subtitle: "HTI HT-19",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Прибор для тепловизионной диагностики.",
    },
    {
      id: "27",
      title: "Перфоратор",
      subtitle: "Makita 2470",
      pricePerDay: 800,
      deposit: 5000,
      description: "Надёжный перфоратор для строительных работ.",
    },
    {
      id: "28",
      title: "Шуруповерт",
      subtitle: "Bosch GSB120-Li",
      pricePerDay: 600,
      deposit: 5000,
      description: "Аккумуляторный шуруповерт для монтажа.",
    },
    {
      id: "29",
      title: "Компрессор 100 л",
      subtitle: "Inforce CE100",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Воздушный компрессор большого объёма.",
    },
    {
      id: "30",
      title: "Сварочный аппарат полуавтомат",
      subtitle: "Сварог Real MIG 200",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Полуавтомат для сварочных работ.",
    },
    {
      id: "31",
      title: "Тепловая пушка",
      subtitle: "Timberk TIH Q2 12M",
      pricePerDay: 600,
      deposit: 5000,
      description: "Электрическая тепловая пушка.",
    },
    {
      id: "32",
      title: "Осушитель 92/1",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "33",
      title: "Осушитель 92/2",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "34",
      title: "Осушитель 92/3",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "35",
      title: "Осушитель 92/4",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "36",
      title: "Осушитель 92/5",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "37",
      title: "Осушитель 92/6",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "38",
      title: "Осушитель 92/7",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "39",
      title: "Осушитель 92/8",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "40",
      title: "Осушитель 92/9",
      subtitle: "Master DH92",
      pricePerDay: 1100,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "41",
      title: "Осушитель 62/1",
      subtitle: "Master DH62",
      pricePerDay: 900,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "42",
      title: "Осушитель 62/2",
      subtitle: "Master DH62",
      pricePerDay: 900,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "43",
      title: "Осушитель 77/1",
      subtitle: "Wilms KT 800",
      pricePerDay: 900,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "44",
      title: "Осушитель 77/2",
      subtitle: "Wilms KT 800",
      pricePerDay: 900,
      deposit: 5000,
      description: "Промышленный осушитель воздуха.",
    },
    {
      id: "45",
      title: "Осушитель 70",
      subtitle: "Dehu-70L",
      pricePerDay: 900,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "46",
      title: "Осушитель 732",
      subtitle: "Master DH732",
      pricePerDay: 800,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "47",
      title: "Осушитель 752/1",
      subtitle: "Master DH752",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "48",
      title: "Осушитель 752/2",
      subtitle: "Master DH752",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "49",
      title: "Осушитель 752/3",
      subtitle: "Master DH752",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "50",
      title: "Осушитель 752/4",
      subtitle: "Master DH752",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "51",
      title: "Осушитель 752/5",
      subtitle: "Master DH752",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "52",
      title: "Осушитель 90",
      subtitle: "Dantherm CDT 90",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "53",
      title: "Осушитель 60",
      subtitle: "ASPRO-DRY60",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "54",
      title: "Осушитель 60",
      subtitle: "ND60-ATT",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "55",
      title: "Осушитель 60",
      subtitle: "ZS60L",
      pricePerDay: 850,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "56",
      title: "Осушитель 50",
      subtitle: "Dehumidifier DB50",
      pricePerDay: 800,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "57",
      title: "Осушитель 500ден",
      subtitle: "Danvex DEN 500i",
      pricePerDay: 800,
      deposit: 5000,
      description: "Осушитель воздуха.",
    },
    {
      id: "58",
      title: "Озонатор",
      subtitle: "Ozonika 20",
      pricePerDay: 3000,
      deposit: 10000,
      description: "Оборудование для озонирования помещений.",
    },
    {
      id: "59",
      title: "Перфоратор",
      subtitle: "Makita 5001C",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Мощный перфоратор для тяжёлых работ.",
    },
    {
      id: "60",
      title: "Генератор",
      subtitle: "CHAMPION GG7501E-3",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Бензиновый генератор.",
    },
    {
      id: "61",
      title: "Мотобур",
      subtitle: "CHAMPION AG252",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Мотобур для бурения грунта.",
    },
    {
      id: "62",
      title: "Мотопомпа",
      subtitle: "FUBAG PG950T",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Мотопомпа для перекачки воды.",
    },
    {
      id: "63",
      title: "Мотопомпа 2",
      subtitle: "FUBAG PG950T",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Мотопомпа для перекачки воды.",
    },
    {
      id: "64",
      title: "Сварочный аппарат",
      subtitle: "Foxweld VARTEG 230",
      pricePerDay: 500,
      deposit: 5000,
      description: "Сварочный аппарат для работ по металлу.",
    },
    {
      id: "65",
      title: "Компрессор",
      subtitle: "Aurora CYCLON-75 TURBO",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Воздушный компрессор.",
    },
    {
      id: "66",
      title: "Желобонакатный станок /1",
      subtitle: "VOLL V-Groover 6",
      pricePerDay: 3000,
      deposit: 15000,
      description: "Станок для желобонакатных работ.",
    },
    {
      id: "67",
      title: "Желобонакатный станок /2",
      subtitle: "Hongli YG12D",
      pricePerDay: 3000,
      deposit: 15000,
      description: "Станок для желобонакатных работ.",
    },
    {
      id: "68",
      title: "Измельчитель веток",
      subtitle: "GBK 150",
      pricePerDay: 7000,
      deposit: 20000,
      description: "Оборудование для измельчения веток.",
    },
    {
      id: "69",
      title: "Измельчитель пней",
      subtitle: "SGR1500E",
      pricePerDay: 6000,
      deposit: 20000,
      description: "Оборудование для удаления пней.",
    },
    {
      id: "70",
      title: "Торцовая пила с протяжкой",
      subtitle: "AEG PS 216 L",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Торцовочная пила для точных распилов.",
    },
    {
      id: "71",
      title: "Пылесос промышленный /1",
      subtitle: "Linolit 322E",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Промышленный пылесос.",
    },
    {
      id: "72",
      title: "Безвоздушный краскопульт",
      subtitle: "GTB-850",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Аппарат для безвоздушной окраски.",
    },
    {
      id: "73",
      title: "Плиткорез электрический",
      subtitle: "Wandeli ZX-1200",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Электрический плиткорез.",
    },
    {
      id: "74",
      title: "Виброрейка 2,5 м",
      subtitle: "VEKTOR VSJ-2.5",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Оборудование для выравнивания бетона.",
    },
    {
      id: "75",
      title: "Плазморез",
      subtitle: "Аврора Джет 40",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Плазморез с компрессором.",
    },
    {
      id: "76",
      title: "Плазморез 2",
      subtitle: "Аврора Джет 40",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Плазморез с компрессором.",
    },
    {
      id: "77",
      title: "Вибратор для бетона",
      subtitle: "Oli EWO 38 RUS",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Оборудование для уплотнения бетона.",
    },
    {
      id: "78",
      title: "Вентилятор 1",
      subtitle: "MASTER DF 20 P",
      pricePerDay: 800,
      deposit: 5000,
      description: "Промышленный вентилятор.",
    },
    {
      id: "79",
      title: "Вентилятор 2",
      subtitle: "MASTER DF 20 P",
      pricePerDay: 800,
      deposit: 5000,
      description: "Промышленный вентилятор.",
    },
    {
      id: "80",
      title: "Газовая пушка 1",
      subtitle: "Gigant GH30FD",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Газовая тепловая пушка.",
    },
    {
      id: "81",
      title: "Газовая пушка 2",
      subtitle: "Gigant GH30FD",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Газовая тепловая пушка.",
    },
    {
      id: "82",
      title: "Газовая пушка 3",
      subtitle: "MCS BLP17M",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Газовая тепловая пушка.",
    },
    {
      id: "83",
      title: "Швонарезчик",
      subtitle: "Слипстоун CS146",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Резчик швов по бетону.",
    },
    {
      id: "84",
      title: "Виброплита 300 кг",
      subtitle: "VS-309",
      pricePerDay: 4000,
      deposit: 15000,
      description: "Тяжёлая виброплита для уплотнения грунта.",
    },
    {
      id: "85",
      title: "Швонарезчик на 900 мм",
      subtitle: "CS3213 Слипстоун",
      pricePerDay: 4000,
      deposit: 15000,
      description: "Мощный швонарезчик.",
    },
    {
      id: "86",
      title: "Шлифмашина по бетону 1",
      subtitle: "Слипстоун GM_122",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Шлифмашина для бетонных поверхностей.",
    },
    {
      id: "87",
      title: "Шлифмашина по бетону 2",
      subtitle: "Слипстоун GM_122",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Шлифмашина для бетонных поверхностей.",
    },
    {
      id: "88",
      title: "Шлифмашина по бетону 3",
      subtitle: "Слипстоун GM_122",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Шлифмашина для бетонных поверхностей.",
    },
    {
      id: "89",
      title: "Перфоратор SDS+",
      subtitle: "BH-2100N",
      pricePerDay: 800,
      deposit: 5000,
      description: "Перфоратор SDS+.",
    },
    {
      id: "90",
      title: "Перфоратор SDS+",
      subtitle: "Зубр П-26-800",
      pricePerDay: 800,
      deposit: 5000,
      description: "Перфоратор SDS+.",
    },
    {
      id: "91",
      title: "Штроборез",
      subtitle: "Зубр ЗШ-П30-1400",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Штроборез для прокладки коммуникаций.",
    },
    {
      id: "92",
      title: "Штроборез",
      subtitle: "Зубр 230 мм",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Штроборез для прокладки коммуникаций.",
    },
    {
      id: "93",
      title: "Миксер",
      subtitle: "Makita",
      pricePerDay: 800,
      deposit: 5000,
      description: "Строительный миксер.",
    },
    {
      id: "94",
      title: "Измеритель влажности",
      subtitle: "Testo",
      pricePerDay: 800,
      deposit: 5000,
      description: "Прибор для измерения влажности.",
    },
    {
      id: "95",
      title: "Сабельная пила",
      subtitle: "Hammer",
      pricePerDay: 800,
      deposit: 5000,
      description: "Сабельная пила для демонтажа и резки.",
    },
    {
      id: "96",
      title: "Бензопила",
      subtitle: "Патриот ПТ3816",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Бензиновая цепная пила.",
    },
    {
      id: "97",
      title: "Пылесос",
      subtitle: "Dexter",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Строительный пылесос.",
    },
    {
      id: "98",
      title: "Мойка высокого давления",
      subtitle: "Karcher K7 Compact",
      pricePerDay: 1300,
      deposit: 5000,
      description: "Аппарат высокого давления.",
    },
    {
      id: "99",
      title: "Вибратор для бетона",
      subtitle: "Дрельного типа",
      pricePerDay: 800,
      deposit: 5000,
      description: "Вибратор для бетона дрельного типа.",
    },
    {
      id: "100",
      title: "Виброплита 100 кг",
      subtitle: "Zitrek",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Виброплита для уплотнения грунта.",
    },
    {
      id: "101",
      title: "Установка алмазного бурения",
      subtitle: "Сатурн ОВ-255",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Установка для алмазного бурения.",
    },
    {
      id: "102",
      title: "Триммер",
      subtitle: "Daewoo DABC 520",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Бензиновый триммер для травы.",
    },
    {
      id: "103",
      title: "Дизельная пушка",
      subtitle: "Ballu",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Дизельная тепловая пушка.",
    },
    {
      id: "104",
      title: "Лампа Лосева",
      subtitle: "Lossew Lamp P2 Ultra Pro",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Специализированная лампа.",
    },
    {
      id: "105",
      title: "Вибротрамбовка",
      subtitle: "Gigant Honda DVT75-H160",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Вибротрамбовка для грунта.",
    },
    {
      id: "106",
      title: "УШМ 125",
      subtitle: "AEG WS 6-125",
      pricePerDay: 700,
      deposit: 5000,
      description: "Углошлифовальная машина.",
    },
    {
      id: "107",
      title: "УШМ 125",
      subtitle: "AEG WS 8-125",
      pricePerDay: 700,
      deposit: 5000,
      description: "Углошлифовальная машина.",
    },
    {
      id: "108",
      title: "УШМ 125",
      subtitle: "AEG WS 13-125 XE",
      pricePerDay: 700,
      deposit: 5000,
      description: "Углошлифовальная машина.",
    },
    {
      id: "109",
      title: "Пылесос строительный",
      subtitle: "ПС 12-35А",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Строительный пылесос.",
    },
    {
      id: "110",
      title: "Пылесос промышленный /3",
      subtitle: "Linolit 612E",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Промышленный пылесос.",
    },
    {
      id: "111",
      title: "Пылесос промышленный /2",
      subtitle: "Linolit 612E",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Промышленный пылесос.",
    },
    {
      id: "112",
      title: "Копер",
      subtitle: "MESSER JH-70",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Бензиновый копер.",
    },
    {
      id: "113",
      title: "Лобзик",
      subtitle: "AEG STEP 100X",
      pricePerDay: 700,
      deposit: 5000,
      description: "Электролобзик.",
    },
    {
      id: "114",
      title: "Бензобур",
      subtitle: "ADA",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Бензобур для грунта.",
    },
    {
      id: "115",
      title: "Электропила",
      subtitle: "Huter ELS-2800",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Электрическая цепная пила.",
    },
    {
      id: "116",
      title: "Компрессор 50 л",
      subtitle: "Inforce BCX-50L",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Воздушный компрессор 50 литров.",
    },
    {
      id: "117",
      title: "Реноватор",
      subtitle: "Зубр Профессионал 550 Вт",
      pricePerDay: 700,
      deposit: 5000,
      description: "Многофункциональный инструмент.",
    },
    {
      id: "118",
      title: "Виброплита 180 кг",
      subtitle: "RedVerg RD-PC180R",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Виброплита для уплотнения грунта.",
    },
    {
      id: "119",
      title: "Шлифмашина по бетону 1",
      subtitle: "Слипстоун GM_245/7.5",
      pricePerDay: 3800,
      deposit: 15000,
      description: "Мощная шлифмашина по бетону.",
    },
    {
      id: "120",
      title: "Шлифмашина по бетону 2",
      subtitle: "Слипстоун GM_245/7.5",
      pricePerDay: 3800,
      deposit: 15000,
      description: "Мощная шлифмашина по бетону.",
    },
    {
      id: "121",
      title: "Шлифмашина по бетону 3",
      subtitle: "Слипстоун GM_245/7.5",
      pricePerDay: 3800,
      deposit: 15000,
      description: "Мощная шлифмашина по бетону.",
    },
    {
      id: "122",
      title: "Шлифмашина по бетону 4",
      subtitle: "Слипстоун GM_245/7.5",
      pricePerDay: 3800,
      deposit: 15000,
      description: "Мощная шлифмашина по бетону.",
    },
    {
      id: "123",
      title: "Отбойный молоток 1",
      subtitle: "DEKO DRGH1800",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Отбойный молоток для демонтажа.",
    },
    {
      id: "124",
      title: "Отбойный молоток 2",
      subtitle: "DEKO DRGH1800",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Отбойный молоток для демонтажа.",
    },
    {
      id: "125",
      title: "Сваекрут",
      subtitle: "REBIR AIE-1206-16/2000ER",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Инструмент для закручивания свай.",
    },
    {
      id: "126",
      title: "Кусторез",
      subtitle: "WP280E WORX",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Кусторез для ухода за зелёными насаждениями.",
    },
    {
      id: "127",
      title: "Отбойный молоток 3",
      subtitle: "Спец 3337",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Отбойный молоток для демонтажа.",
    },
    {
      id: "128",
      title: "Швонарезчик электрический",
      subtitle: "Слипстоун CS144E",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Электрический швонарезчик.",
    },
    {
      id: "129",
      title: "Аэратор для газона",
      subtitle: "ECO SCG400",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Аэратор для ухода за газоном.",
    },
    {
      id: "130",
      title: "Мотобур",
      subtitle: "GROUND DRILL-16 HERCULES",
      pricePerDay: 1800,
      deposit: 10000,
      description: "Мотобур для бурения грунта.",
    },
    {
      id: "131",
      title: "Электропушка",
      subtitle: "BALLU BHP-P-3",
      pricePerDay: 350,
      deposit: 5000,
      description: "Электрическая тепловая пушка.",
    },
    {
      id: "132",
      title: "Uponor головки 16/20/25/32",
      subtitle: "Uponor Q&E",
      pricePerDay: 600,
      deposit: 5000,
      description: "Комплект головок для монтажа труб.",
    },
    {
      id: "133",
      title: "Прессклещи электро 15/18/22/28",
      subtitle: "Geberit Mapress",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Электропресс для монтажных работ.",
    },
    {
      id: "134",
      title: "Аэратор для газона",
      subtitle: "DAEWOO DSC 4000",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Бензиновый вертикуттер.",
    },
    {
      id: "135",
      title: "Заклепочник",
      subtitle: "TAC 500A",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Инструмент для установки заклёпок.",
    },
    {
      id: "136",
      title: "Таль 10 т 12 м",
      subtitle: "Без модели",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Таль для подъёма грузов.",
    },
    {
      id: "137",
      title: "Копер",
      subtitle: "ТСС-95GPDA",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Копер для монтажных работ.",
    },
    {
      id: "138",
      title: "Циркулярная пила",
      subtitle: "AEG 66-2",
      pricePerDay: 800,
      deposit: 5000,
      description: "Ручная циркулярная пила.",
    },
    {
      id: "139",
      title: "Дрель Makita",
      subtitle: "HP1620",
      pricePerDay: 600,
      deposit: 5000,
      description: "Электродрель.",
    },
    {
      id: "140",
      title: "Моющий пылесос",
      subtitle: "TOR LC-20SC",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Моющий пылесос для глубокой уборки.",
    },
    {
      id: "141",
      title: "Снегоуборщик",
      subtitle: "PATRIOT PS 602 E",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Снегоуборочная машина.",
    },
    {
      id: "142",
      title: "Плиткорез ручной 600",
      subtitle: "Без модели",
      pricePerDay: 800,
      deposit: 5000,
      description: "Ручной плиткорез.",
    },
    {
      id: "143",
      title: "Лазерный уровень",
      subtitle: "Без модели",
      pricePerDay: 800,
      deposit: 5000,
      description: "Лазерный нивелир.",
    },
    {
      id: "144",
      title: "Плиткорез ручной 800",
      subtitle: "Без модели",
      pricePerDay: 800,
      deposit: 5000,
      description: "Ручной плиткорез.",
    },
    {
      id: "145",
      title: "Затирочная машина по бетону",
      subtitle: "Вертолет",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Машина для затирки бетонных поверхностей.",
    },
    {
      id: "146",
      title: "Улитка 1",
      subtitle: "АС 900",
      pricePerDay: 800,
      deposit: 5000,
      description: "Специализированное оборудование.",
    },
    {
      id: "147",
      title: "Улитка 2",
      subtitle: "Без модели",
      pricePerDay: 800,
      deposit: 5000,
      description: "Специализированное оборудование.",
    },
    {
      id: "148",
      title: "Лестница",
      subtitle: "Без модели",
      pricePerDay: 1000,
      deposit: 5000,
      description: "Лестница для строительных и бытовых работ.",
    },
    {
      id: "149",
      title: "Сеялка",
      subtitle: "Без модели",
      pricePerDay: 500,
      deposit: 5000,
      description: "Сеялка для посевных работ.",
    },
    {
      id: "150",
      title: "Стенорез",
      subtitle: "Kenrus DC 425",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Оборудование для резки стен.",
    },
    {
      id: "151",
      title: "Пескоструй",
      subtitle: "Булат и компрессор",
      pricePerDay: 2000,
      deposit: 10000,
      description: "Пескоструйное оборудование.",
    },
    {
      id: "152",
      title: "Виброплита 152 кг",
      subtitle: "Champion PC1645 RH",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Виброплита для уплотнения грунта.",
    },
    {
      id: "153",
      title: "Виброплита 215 кг",
      subtitle: "Masalta MS250-4",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Виброплита для уплотнения грунта.",
    },
    {
      id: "154",
      title: "Дровокол",
      subtitle: "Champion LSH 5001",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Оборудование для колки дров.",
    },
    {
      id: "155",
      title: "Дизельный калорифер",
      subtitle: "PATRIOT DTC 303i",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Дизельный калорифер непрямого нагрева.",
    },
    {
      id: "156",
      title: "Дизельный калорифер 2",
      subtitle: "PATRIOT DTC 303i",
      pricePerDay: 2500,
      deposit: 10000,
      description: "Дизельный калорифер непрямого нагрева.",
    },
    {
      id: "157",
      title: "Подстанция трансформаторная",
      subtitle: "КТПТО-80-У1",
      pricePerDay: 1800,
      deposit: 10000,
      description: "Трансформаторная подстанция для прогрева бетона.",
    },
    {
      id: "158",
      title: "Трансформатор для прогрева бетона",
      subtitle: "ТСДЗ-80/0,38-У2",
      pricePerDay: 1500,
      deposit: 10000,
      description: "Оборудование для прогрева бетона.",
    },
  ];